version: "3.9"

services:
  db:
    image: postgres:17
    container_name: fintellect-db
    restart: always
    environment:
      POSTGRES_DB: fintellect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
