CREATE TABLE staging_users (
    "Timestamp" TIMESTAMP,
    email TEXT,
    name_stud TEXT,
    gender TEXT,
    age INTEGER,
    university TEXT,
    city TEXT,
    monthly_budget NUMERIC,
    rent NUMERIC,
    grocery NUMERIC,
    transportation NUMERIC,
    personal NUMERIC,
    misc NUMERIC,
    ef_knowledge TEXT,
    target_saving NUMERIC,
    wage_per_hour INTEGER,
    tuition_fees_due_date DATE,
    insurance_due_date DATE,
    subway TEXT,
    starbucks TEXT,
    tacobell TEXT,
    walmart TEXT,
    notification_preferences TEXT
);